;**********************************************************************
;**********************************************************************
;**                                                                  **
;**        (C)Copyright 1985-2009, American Megatrends, Inc.         **
;**                                                                  **
;**                       All Rights Reserved.                       **
;**                                                                  **
;**             5555 Oakbrook Pkwy, Norcross, GA 30093               **
;**                                                                  **
;**                       Phone: (770)-246-8600                      **
;**                                                                  **
;**********************************************************************
;**********************************************************************

;**********************************************************************
; $Header: /Alaska/BIN/Modules/ACPI/Template/Core/MpPciIrq.asm 3     3/26/09 4:51p Oleksiyy $
;
; $Revision: 3 $
;
; $Date: 3/26/09 4:51p $
;**********************************************************************
; Revision History
; ----------------
; $Log: /Alaska/BIN/Modules/ACPI/Template/Core/MpPciIrq.asm $
; 
; 3     3/26/09 4:51p Oleksiyy
; New ACPI Core implementation - improves logic, execution time and
; memory usage of ACPI module.
; 
; 2     2/08/07 12:47p Artems
; 
; 1     2/06/07 4:54p Artems
; 
;**********************************************************************
;<AMI_FHDR_START>
;
; Name:	MpPciIrq.asm
;
; Description:	This file includes MPS related tables, generated by AMISDL
;
;<AMI_FHDR_END>
;**********************************************************************

IFNDEF EFIx64
.586P
option language:c
ENDIF

; MPS PCI IRQ - APIC description table
;------------------------------------------------------------------------------
MP_IRI	STRUC
	PciBusNumber        db  ?
    DeviceNumber        db  ?
    IntA_ApicItin       db  ?
    IntA_ApicId         db  ?
    IntB_ApicItin       db  ?
    IntB_ApicId         db  ?
    IntC_ApicItin       db  ?
    IntC_ApicId         db  ?
    IntD_ApicItin       db  ?
    IntD_ApicId         db  ?
    Reserved            db  ?
MP_IRI	ENDS

MP_IAI  STRUC
    ApicAddress         dd  ?
    ApicId              db  ?
    Reserved            db  ?
MP_IAI  ENDS

;IFDEF MpsTable_SUPPORT

IFNDEF EFIx64
MPSDATA_SEG SEGMENT USE32 'DATA'
ELSE
MPSDATA_SEG SEGMENT 'DATA'
ENDIF
	include mppciirq.inc
MPSDATA_SEG ENDS

;ENDIF

end



;**********************************************************************
;**********************************************************************
;**                                                                  **
;**        (C)Copyright 1985-2009, American Megatrends, Inc.         **
;**                                                                  **
;**                       All Rights Reserved.                       **
;**                                                                  **
;**             5555 Oakbrook Pkwy, Norcross, GA 30093               **
;**                                                                  **
;**                       Phone: (770)-246-8600                      **
;**                                                                  **
;**********************************************************************
;**********************************************************************