#ifndef _PEI_FLUSH_INSTRUCTION_CACHE_GUID_H_
#define _PEI_FLUSH_INSTRUCTION_CACHE_GUID_H_

#define EFI_PEI_FLUSH_INSTRUCTION_CACHE_GUID  \
  { 0xd8117cfc, 0x94a6, 0x11d4, 0x9a, 0x3a, 0x0, 0x90, 0x27, 0x3f, 0xc1, 0x4d }

EFI_FORWARD_DECLARATION (EFI_PEI_FLUSH_INSTRUCTION_CACHE_PROTOCOL);

typedef 
EFI_STATUS
(EFIAPI *EFI_PEI_FLUSH_INSTRUCTION_CACHE_FLUSH) (
  IN EFI_PEI_FLUSH_INSTRUCTION_CACHE_PROTOCOL  *This,
  IN EFI_PHYSICAL_ADDRESS                              Start,
  IN UINT64                                            Length
  );

typedef struct _EFI_PEI_FLUSH_INSTRUCTION_CACHE_PROTOCOL {
  EFI_PEI_FLUSH_INSTRUCTION_CACHE_FLUSH  Flush;
} EFI_PEI_FLUSH_INSTRUCTION_CACHE_PROTOCOL;

extern EFI_GUID gEfiPeiFlushInstructionCacheGuid;

#endif
