/** @file
  Processes ASF messages

@copyright
  Copyright (c) 2010 - 2012 Intel Corporation. All rights
  reserved This software and associated documentation (if any)
  is furnished under a license and may only be used or copied in
  accordance with the terms of the license. Except as permitted
  by such license, no part of this software or documentation may
  be reproduced, stored in a retrieval system, or transmitted in
  any form or by any means without the express written consent
  of Intel Corporation.

  This file contains an 'Intel Peripheral Driver' and uniquely
  identified as "Intel Reference Module" and is
  licensed for Intel CPUs and chipsets under the terms of your
  license agreement with Intel or your vendor.  This file may
  be modified by the user, subject to additional terms of the
  license agreement
**/
EFI_ASF_DATA_HUB_MAP      mAsfProgressDataHubMap[] = {
  {
    EfiAsfMessageBiosPresent,
    EFI_COMPUTING_UNIT_HOST_PROCESSOR | EFI_CU_HP_PC_POWER_ON_INIT
  },
  {
    EfiAsfMessageMemInit,
    EFI_COMPUTING_UNIT_MEMORY | EFI_CU_HP_PC_RAM_INIT
  },
  {
    EfiAsfMessageMemInitDone,
    EFI_COMPUTING_UNIT_MEMORY | EFI_CU_PC_INIT_END
  },
  {
    EfiAsfMessageCacheInit,
    EFI_COMPUTING_UNIT_HOST_PROCESSOR | EFI_CU_HP_PC_CACHE_INIT
  },
  {
    EfiAsfMessageSmbusInit,
    EFI_IO_BUS_SMBUS | EFI_P_PC_ENABLE
  },
  {
    EfiAsfMessageOSWakeVector,
    EFI_SOFTWARE_PEI_MODULE | EFI_SW_DXE_RT_PC_S3
  },
  {
    EfiAsfMessageMotherBoardInit,
    EFI_COMPUTING_UNIT_CHIPSET | EFI_CU_PC_INIT_BEGIN
  },
  {
    EfiAsfMessageBspInit,
    EFI_COMPUTING_UNIT_HOST_PROCESSOR | EFI_CU_HP_PC_BSP_SELECT
  },
#ifndef ASF_PEI
  {
    EfiAsfMessageHddInit,
    EFI_PERIPHERAL_FIXED_MEDIA | EFI_P_PC_ENABLE
  },
  {
    EfiAsfMessageApInit,
    EFI_COMPUTING_UNIT_HOST_PROCESSOR | EFI_CU_HP_PC_AP_INIT
  },
  {
    EfiAsfMessageUserAuthentication,
    EFI_SOFTWARE_DXE_BS_DRIVER | EFI_SW_PC_AUTHENTICATE_BEGIN
  },
  {
    EfiAsfMessageUserInitSetup,
    EFI_SOFTWARE_DXE_BS_DRIVER | EFI_SW_PC_USER_SETUP
  },
  {
    EfiAsfMessageUsbResourceConfig,
    EFI_IO_BUS_USB | EFI_P_PC_ENABLE
  },
  {
    EfiAsfMessagePciResourceConfig,
    EFI_IO_BUS_PCI | EFI_IOB_PCI_PC_BUS_ENUM
  },
  {
    EfiAsfMessageOptionRomInit,
    EFI_SOFTWARE_DXE_BS_DRIVER | EFI_SW_DXE_BS_PC_LEGACY_OPROM_INIT
  },
  {
    EfiAsfMessageVideoInit,
    EFI_PERIPHERAL_LOCAL_CONSOLE | EFI_P_PC_ENABLE
  },
  {
    EfiAsfMessageKbcInit,
    EFI_PERIPHERAL_KEYBOARD | EFI_P_PC_ENABLE
  },
  {
    EfiAsfMessageEmControllerInit,
    EFI_PERIPHERAL_EMBEDDED_CONTROLLER | EFI_P_PC_INIT
  },
  {
    EfiAsfMessageDockAttached,
    EFI_PERIPHERAL_DOCK | EFI_P_PC_INIT
  },
  {
    EfiAsfMessageEnableDock,
    EFI_PERIPHERAL_DOCK | EFI_P_PC_ENABLE
  },
  {
    EfiAsfMessageDockEject,
    EFI_PERIPHERAL_DOCK | EFI_P_PC_RESET
  },
  {
    EfiAsfMessageDisableDock,
    EFI_PERIPHERAL_DOCK | EFI_P_PC_DISABLE
  },
  {
    EfiAsfMessageFdcInit,
    EFI_PERIPHERAL_REMOVABLE_MEDIA | EFI_P_PC_ENABLE
  },
  {
    EfiAsfMessageKeyboardTest,
    EFI_PERIPHERAL_KEYBOARD | EFI_P_KEYBOARD_PC_SELF_TEST
  },
  {
    EfiAsfMessageMouseTest,
    EFI_PERIPHERAL_MOUSE | EFI_P_MOUSE_PC_SELF_TEST
  },
  {
    EfiAsfMessageAmtBxDone,
    EFI_SOFTWARE_UNSPECIFIED | EFI_SW_DXE_AMTBX_OPROM_DONE
  },
  {
    EfiAsfMessageBatteryPresenceDetected,
    EFI_PERIPHERAL_BATTERY | EFI_P_PC_PRESENCE_DETECT
  },
#endif
};

EFI_ASF_DATA_HUB_MAP      mAsfErrorDataHubMap[] = {
  {
    EfiAsfMessageNoMemory,
    EFI_COMPUTING_UNIT_MEMORY | EFI_CU_MEMORY_EC_NONE_DETECTED
  },
  {
    EfiAsfMessageMemoryFailure,
    EFI_COMPUTING_UNIT_MEMORY | EFI_CU_MEMORY_EC_NONE_USEFUL
  },
  {
    EfiAsfMessageBoardFailure,
    EFI_COMPUTING_UNIT_CHIPSET | EFI_CU_EC_NOT_CONFIGURED
  },
  {
    EfiAsfMessageFirmwareCorruption,
    EFI_SOFTWARE_PEI_MODULE | EFI_SW_PEI_CORE_EC_DXE_CORRUPT
  },
  {
    EfiAsfMessageChassisIntrusion,
    EFI_COMPUTING_UNIT_CHIPSET | EFI_CU_CHIPSET_PC_INTRUDER_DETECT
  },
#ifndef ASF_PEI
  {
    EfiAsfMessageHddFailure,
    EFI_PERIPHERAL_FIXED_MEDIA | EFI_P_EC_NOT_DETECTED
  },
  {
    EfiAsfMessageFdcFailure,
    EFI_PERIPHERAL_REMOVABLE_MEDIA | EFI_P_EC_CONTROLLER_ERROR
  },
  {
    EfiAsfMessageHdcFailure,
    EFI_PERIPHERAL_FIXED_MEDIA | EFI_P_EC_CONTROLLER_ERROR
  },
  {
    EfiAsfMessageKbdFailure,
    EFI_PERIPHERAL_KEYBOARD | EFI_P_EC_NOT_DETECTED
  },
  {
    EfiAsfMessageNoFdd,
    EFI_PERIPHERAL_REMOVABLE_MEDIA | EFI_P_EC_NOT_DETECTED
  },
  {
    EfiAsfMessageVideoControllerFailure,
    EFI_PERIPHERAL_LOCAL_CONSOLE | EFI_P_EC_CONTROLLER_ERROR
  },
  {
    EfiAsfMessageNoVideo,
    EFI_PERIPHERAL_LOCAL_CONSOLE | EFI_P_EC_NOT_DETECTED
  },
  {
    EfiAsfMessageCpuVidMismatch,
    EFI_COMPUTING_UNIT_HOST_PROCESSOR | EFI_CU_HP_EC_VID_MISMATCH
  },
  {
    EfiAsfMessageCpuSpeedMatchingFailure,
    EFI_COMPUTING_UNIT_HOST_PROCESSOR | EFI_CU_HP_EC_SPEED_MATCHING_FAILURE
  },
  {
    EfiAsfMessageNoBootMedia,
    EFI_SOFTWARE_DXE_BS_DRIVER | EFI_SW_DXE_BS_EC_NO_BOOT_MEDIA
  },
  {
    EfiAsfMessageUserAuthenticationInvalid,
    EFI_SOFTWARE_DXE_BS_DRIVER | EFI_SW_DXE_BS_EC_AUTHENTICATE_USER_INVALID
  },
  {
    EfiAsfMessageHddAuthenticationInvalid,
    EFI_SOFTWARE_DXE_BS_DRIVER | EFI_SW_DXE_BS_EC_AUTHENTICATE_HDD_INVALID,
  },
  {
    EfiAsfMessageTemperatureGenericCritical,
    EFI_PERIPHERAL_TEMPERATURE | EFI_P_TEMERATURE_EC_GENERIC_CRITICAL
  },
  {
    EfiAsfMessageTemperatureOverCritical,
    EFI_PERIPHERAL_TEMPERATURE | EFI_P_TEMERATURE_EC_OVER_CRITICAL
  },
  {
    EfiAsfMessageTemperatureUnderCritical,
    EFI_PERIPHERAL_TEMPERATURE | EFI_P_TEMERATURE_EC_UNDER_CRITICAL
  },
  {
    EfiAsfMessageVoltageGenericCritical,
    EFI_PERIPHERAL_VOLTAGE | EFI_P_VOLTAGE_EC_GENERIC_CRITICAL
  },
  {
    EfiAsfMessageVoltageOverCritical,
    EFI_PERIPHERAL_VOLTAGE | EFI_P_VOLTAGE_EC_OVER_CRITICAL
  },
  {
    EfiAsfMessageVoltageUnderCritical,
    EFI_PERIPHERAL_VOLTAGE | EFI_P_VOLTAGE_EC_UNDER_CRITICAL
  },
  {
    EfiAsfMessageFanGenericCritical,
    EFI_PERIPHERAL_FAN | EFI_P_FAN_EC_GENERIC_CRITICAL
  },
  {
    EfiAsfMessageFanPredictiveFailure,
    EFI_PERIPHERAL_FAN | EFI_P_FAN_EC_PREDICTIVE_FAILURE
  },
  {
    EfiAsfMessageFanLowSpeedCritical,
    EFI_PERIPHERAL_FAN | EFI_P_FAN_EC_LOW_SPEED_CRITICAL
  },
  {
    EfiAsfMessageBatteryLowCritical,
    EFI_PERIPHERAL_BATTERY | EFI_P_BATTERY_EC_LOW_CRITICAL
  },
  {
    EfiAsfMessageTemperatureGenericWarning,
    EFI_PERIPHERAL_TEMPERATURE | EFI_P_TEMERATURE_PC_GENERIC_WARNING
  },
  {
    EfiAsfMessageTemperatureOverWarning,
    EFI_PERIPHERAL_TEMPERATURE | EFI_P_TEMERATURE_PC_OVER_WARNING
  },
  {
    EfiAsfMessageTemperatureUnderWarning,
    EFI_PERIPHERAL_TEMPERATURE | EFI_P_TEMERATURE_PC_UNDER_WARNING
  },
  {
    EfiAsfMessageFanLowSpeedWarning,
    EFI_PERIPHERAL_FAN | EFI_P_FAN_PC_LOW_SPEED_WARNING
  },
  {
    EfiAsfMessageBatteryLowWarning,
    EFI_PERIPHERAL_BATTERY | EFI_P_BATTERY_PC_LOW_WARNING
  },
  {
    EfiAsfMessagePowerFailure,
    EFI_PERIPHERAL_POWER_SUPPLY | EFI_P_BATTERY_PC_LOW_WARNING
  },
  {
    EfiAsfMessageAmtBxNotStarted,
    EFI_SOFTWARE_UNSPECIFIED | EFI_SW_DXE_AMTBX_OPROM_NOT_STARTED
  },
  {
    EfiAsfMessageAmtBxSleepS4ReportedNotTaken,
    EFI_SOFTWARE_UNSPECIFIED | EFI_SW_DXE_AMTBX_SLEEP_S4_NOT_TAKEN
  },
  {
    EfiAsfMessageAmtBxSleepS5ReportedNotTaken,
    EFI_SOFTWARE_UNSPECIFIED | EFI_SW_DXE_AMTBX_SLEEP_S5_NOT_TAKEN
  },
  {
    EfiAsfMessageAmtBxSleepUnspecifiedReportedNotTaken,
    EFI_SOFTWARE_UNSPECIFIED | EFI_SW_DXE_AMTBX_SLEEP_UNSPECD_NOT_TAKEN
  },
  {
    EfiAsfMessageAmtBxErrActionIntF,
    EFI_SOFTWARE_UNSPECIFIED | EFI_SW_DXE_AMTBX_ERROR_ACTION_INTF
  },
  {
    EfiAsfMessageAmtBxErrActionInv,
    EFI_SOFTWARE_UNSPECIFIED | EFI_SW_DXE_AMTBX_ERROR_ACTION_INV
  },
  {
    EfiAsfMessageAmtBxErrActionSetup,
    EFI_SOFTWARE_UNSPECIFIED | EFI_SW_DXE_AMTBX_ERROR_ACTION_SETUP
  },
  {
    EfiAsfMessageAmtBxErrActionFailure,
    EFI_SOFTWARE_UNSPECIFIED | EFI_SW_DXE_AMTBX_ERROR_ACTION_FAIL
  },
  {
    EfiAsfMessageAmtBxErrActionUnspecified,
    EFI_SOFTWARE_UNSPECIFIED | EFI_SW_DXE_AMTBX_ERROR_ACTION_UNSPECD
  },
  {
    EfiAsfMessageAmtBxOtherUnspecified,
    EFI_SOFTWARE_UNSPECIFIED | EFI_SW_DXE_AMTBX_OTHER_UNSPECD
  },
#endif
};

EFI_ASF_FRAMEWORK_MESSAGE mAsfFrameworkMessage[] = {
  {
    EfiAsfMessageBiosPresent,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_ENTITY_PRESENCE,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      0xFF,
      0xFF,
      EFI_ASF_ENTITY_BIOS,
      0,
      0x40,
      EFI_ASF_FP_BOARD_INIT
    }
  },
  {
    EfiAsfMessageMemInit,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_MEMORY,
      0,  // Instance
      EFI_ASF_FP_EVENT_DATA0,
      EFI_ASF_FP_MEMORY_INIT
    }
  },
  {
    EfiAsfMessageMemInitDone,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS | 0x80,  // Exit
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_MEMORY,
      0,  // Instance
      EFI_ASF_FP_EVENT_DATA0,
      EFI_ASF_FP_MEMORY_INIT
    }
  },
  {
    EfiAsfMessageCacheInit,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_PROCESSOR,
      0,  // Instance
      EFI_ASF_FP_EVENT_DATA0,
      EFI_ASF_FP_CACHE_INIT
    }
  },
  {
    EfiAsfMessageSmbusInit,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
      EFI_ASF_FP_EVENT_DATA0,
      EFI_ASF_FP_SMBUS_INIT
    }
  },
  {
    EfiAsfMessageOSWakeVector,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_UNSPECIFIED,
      0,  // Instance
      EFI_ASF_FP_EVENT_DATA0,
      EFI_ASF_FP_WAKE_OS
    }
  },
  {
    EfiAsfMessageMotherBoardInit,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
      EFI_ASF_FP_EVENT_DATA0,
      EFI_ASF_FP_BOARD_INIT
    }
  },
  //
  // Error Event
  //
  {
    EfiAsfMessageNoMemory,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_ERROR,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONCRITICAL,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_MEMORY,
      0,  // Instance
      EFI_ASF_FE_EVENT_DATA0,
      EFI_ASF_FE_NO_MEMORY
    }
  },
  {
    EfiAsfMessageMemoryFailure,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_ERROR,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONCRITICAL,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_MEMORY,
      0,  // Instance
      EFI_ASF_FE_EVENT_DATA0,
      EFI_ASF_FE_MEMORY_FAILURE
    }
  },
  {
    EfiAsfMessageBoardFailure,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_ERROR,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONRECOVERABLE,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
      EFI_ASF_FE_EVENT_DATA0,
      EFI_ASF_FE_BOARD_FAILURE
    }
  },
  {
    EfiAsfMessageFirmwareCorruption,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_ERROR,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONCRITICAL,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Insnce
      EFI_ASF_FE_EVENT_DATA0,
      EFI_ASF_FE_ROM_CORRUPTED
    }
  },
  //
  // Chassis Intrusion
  //
  {
    EfiAsfMessageChassisIntrusion,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_CHASSIS_INTRUSION,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_CHASSIS_INTRUSION_GENERIC,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
    }
  },
#ifndef ASF_PEI
  //
  // Progress Event
  //
  {
    EfiAsfMessageHddInit,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_DISK,
      0,  // Instance
      EFI_ASF_FP_EVENT_DATA0,
      EFI_ASF_FP_HDD_INIT
    }
  },
  {
    EfiAsfMessageApInit,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_PROCESSOR,
      0,  // Instance
      EFI_ASF_FP_EVENT_DATA0,
      EFI_ASF_FP_AP_INIT
    }
  },
  {
    EfiAsfMessageUserAuthentication,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_BIOS,
      0,  // Instance
      EFI_ASF_FP_EVENT_DATA0,
      EFI_ASF_FP_USER_AUTHENTICATION
    }
  },
  {
    EfiAsfMessageUserInitSetup,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_BIOS,
      0,  // Instance
      EFI_ASF_FP_EVENT_DATA0,
      EFI_ASF_FP_USER_SETUP
    }
  },
  {
    EfiAsfMessageUsbResourceConfig,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_BIOS,
      0,  // Instance
      EFI_ASF_FP_EVENT_DATA0,
      EFI_ASF_FP_USB_RESOURCE_CONFIG
    }
  },
  {
    EfiAsfMessagePciResourceConfig,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_BIOS,
      0,  // Instance
      EFI_ASF_FP_EVENT_DATA0,
      EFI_ASF_FP_PCI_RESOURCE_CONFIG
    }
  },
  {
    EfiAsfMessageOptionRomInit,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_ADDIN_CARD,
      0,  // Instance
      EFI_ASF_FP_EVENT_DATA0,
      EFI_ASF_FP_OPTION_ROM_INIT
    }
  },
  {
    EfiAsfMessageVideoInit,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
      EFI_ASF_FP_EVENT_DATA0,
      EFI_ASF_FP_VIDEO_INIT
    }
  },
  {
    EfiAsfMessageKbcInit,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
      EFI_ASF_FP_EVENT_DATA0,
      EFI_ASF_FP_KBC_INIT
    }
  },
  {
    EfiAsfMessageEmControllerInit,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
      EFI_ASF_FP_EVENT_DATA0,
      EFI_ASF_FP_EC_INIT
    }
  },
  {
    EfiAsfMessageDockAttached,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
      EFI_ASF_FP_EVENT_DATA0,
      EFI_ASF_FP_ATTACH_DOCK
    }
  },
  {
    EfiAsfMessageEnableDock,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
      EFI_ASF_FP_EVENT_DATA0,
      EFI_ASF_FP_ENABLE_DOCK
    }
  },
  {
    EfiAsfMessageDockEject,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
      EFI_ASF_FP_EVENT_DATA0,
      EFI_ASF_FP_EJECT_DOCK
    }
  },
  {
    EfiAsfMessageDisableDock,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
      EFI_ASF_FP_EVENT_DATA0,
      EFI_ASF_FP_DISABLE_DOCK
    }
  },
  {
    EfiAsfMessageFdcInit,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
      EFI_ASF_FP_EVENT_DATA0,
      EFI_ASF_FP_FDC_INIT
    }
  },
  {
    EfiAsfMessageKeyboardTest,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
      EFI_ASF_FP_EVENT_DATA0,
      EFI_ASF_FP_KBD_TEST
    }
  },
  {
    EfiAsfMessageMouseTest,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
      EFI_ASF_FP_EVENT_DATA0,
      EFI_ASF_FP_MOUSE_TEST
    }
  },
  {
    EfiAsfMessageBspInit,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_PROCESSOR,
      0,  // Instance
      EFI_ASF_FP_EVENT_DATA0,
      EFI_ASF_FP_BSP_INIT
    }
  },
  //
  // Error Event
  //
  {
    EfiAsfMessageHddFailure,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_ERROR,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONRECOVERABLE,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_DISK,
      0,  // Instance
      EFI_ASF_FE_EVENT_DATA0,
      EFI_ASF_FE_HDD_FAILURE
    }
  },
  {
    EfiAsfMessageFdcFailure,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_ERROR,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONRECOVERABLE,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_DISK,
      0,  // Instance
      EFI_ASF_FE_EVENT_DATA0,
      EFI_ASF_FE_FDC_FAILURE
    }
  },
  {
    EfiAsfMessageHdcFailure,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_ERROR,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONRECOVERABLE,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_DISK,
      0,  // Instance
      EFI_ASF_FE_EVENT_DATA0,
      EFI_ASF_FE_HDC_FAILURE
    }
  },
  {
    EfiAsfMessageKbdFailure,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_ERROR,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONCRITICAL,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
      EFI_ASF_FE_EVENT_DATA0,
      EFI_ASF_FE_KBD_FAILURE
    }
  },
  {
    EfiAsfMessageNoFdd,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_ERROR,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONRECOVERABLE,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_DISK,
      0,  // Instance
      EFI_ASF_FE_EVENT_DATA0,
      EFI_ASF_FE_REMOVABLE_BOOT_MEDIA_NOT_FOUND
    }
  },
  {
    EfiAsfMessageVideoControllerFailure,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_ERROR,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONRECOVERABLE,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_DISK,
      0,  // Instance
      EFI_ASF_FE_EVENT_DATA0,
      EFI_ASF_FE_VIDEO_CONTROLLER_FAILURE
    }
  },
  {
    EfiAsfMessageNoVideo,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_ERROR,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONCRITICAL,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
      EFI_ASF_FE_EVENT_DATA0,
      EFI_ASF_FE_VIDEO_DEVICE_NOT_FOUND
    }
  },
  {
    EfiAsfMessageCpuVidMismatch,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_ERROR,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONCRITICAL,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_PROCESSOR,
      0,  // Instance
      EFI_ASF_FE_EVENT_DATA0,
      EFI_ASF_FE_CPU_VOLTAGE_FAILURE
    }
  },
  {
    EfiAsfMessageCpuSpeedMatchingFailure,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_ERROR,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONCRITICAL,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_PROCESSOR,
      0,  // Instance
      EFI_ASF_FE_EVENT_DATA0,
      EFI_ASF_FE_CPU_MISMATCH_FAILURE
    }
  },
  {
    EfiAsfMessageUserAuthenticationInvalid,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_RETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SECURITY_VIOLATION,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SECURITY_VIOLATION_USER_PASSWORD,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONCRITICAL,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_BIOS,
      0,  // Instance
    }
  },
  {
    EfiAsfMessageHddAuthenticationInvalid,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_RETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SECURITY_VIOLATION,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SECURITY_VIOLATION_OTHER_PASSWORD,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONCRITICAL,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_BIOS,
      0,  // Instance
    }
  },
  //
  // Boot Error
  //
  {
    EfiAsfMessageNoBootMedia,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_ERROR,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONRECOVERABLE,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_DISK,
      0,  // Insnce
      EFI_ASF_FE_EVENT_DATA0,
      EFI_ASF_FE_REMOVABLE_BOOT_MEDIA_NOT_FOUND
    }
  },
  {
    EfiAsfMessageAmtBxDone,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_PROGRESS,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      0xFF,
      0xFF,
      EFI_ASF_ENTITY_INTEL_AMT,
      0,
      0x40,
      EFI_ASF_FP_AMTBX_INIT
    }
  },
  {
    EfiAsfMessageAmtBxNotStarted,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_ERROR,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONRECOVERABLE,
      0xFF,
      0xFF,
      EFI_ASF_ENTITY_INTEL_AMT,
      0,
      0x40,
      EFI_ASF_FE_AMTBX_FAILURE
    }
  },
  {
    EfiAsfMessageAmtBxSleepS4ReportedNotTaken,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_ERROR,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONCRITICAL,
      0xFF,
      0xFF,
      EFI_ASF_ENTITY_INTEL_AMT,
      0,
      0x40,
      EFI_ASF_FE_AMTBX_FAILURE
    }
  },
  {
    EfiAsfMessageAmtBxSleepS5ReportedNotTaken,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_ERROR,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONCRITICAL,
      0xFF,
      0xFF,
      EFI_ASF_ENTITY_INTEL_AMT,
      0,
      0x40,
      EFI_ASF_FE_AMTBX_FAILURE
    }
  },
  {
    EfiAsfMessageAmtBxSleepUnspecifiedReportedNotTaken,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_ERROR,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONCRITICAL,
      0xFF,
      0xFF,
      EFI_ASF_ENTITY_INTEL_AMT,
      0,
      0x40,
      EFI_ASF_FE_AMTBX_FAILURE
    }
  },
  {
    EfiAsfMessageAmtBxErrActionIntF,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_ERROR,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONRECOVERABLE,
      0xFF,
      0xFF,
      EFI_ASF_ENTITY_INTEL_AMT,
      0,
      0x40,
      EFI_ASF_FE_AMTBX_FAILURE
    }
  },
  {
    EfiAsfMessageAmtBxErrActionInv,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_ERROR,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONCRITICAL,
      0xFF,
      0xFF,
      EFI_ASF_ENTITY_INTEL_AMT,
      0,
      0x40,
      EFI_ASF_FE_AMTBX_FAILURE
    }
  },
  {
    EfiAsfMessageAmtBxErrActionSetup,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_ERROR,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONCRITICAL,
      0xFF,
      0xFF,
      EFI_ASF_ENTITY_INTEL_AMT,
      0,
      0x40,
      EFI_ASF_FE_AMTBX_FAILURE
    }
  },
  {
    EfiAsfMessageAmtBxErrActionFailure,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_ERROR,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONRECOVERABLE,
      0xFF,
      0xFF,
      EFI_ASF_ENTITY_INTEL_AMT,
      0,
      0x40,
      EFI_ASF_FE_AMTBX_FAILURE
    }
  },
  {
    EfiAsfMessageAmtBxErrActionUnspecified,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_ERROR,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONCRITICAL,
      0xFF,
      0xFF,
      EFI_ASF_ENTITY_INTEL_AMT,
      0,
      0x40,
      EFI_ASF_FE_AMTBX_FAILURE
    }
  },
  {
    EfiAsfMessageAmtBxOtherUnspecified,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_SYS_FW_ERR_PROG,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_SYS_FW_ERROR,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONCRITICAL,
      0xFF,
      0xFF,
      EFI_ASF_ENTITY_INTEL_AMT,
      0,
      0x40,
      EFI_ASF_FE_AMTBX_FAILURE
    }
  },
  //
  // Temperature
  //
  {
    EfiAsfMessageTemperatureGenericCritical,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_TEMPERATURE,
      EFI_ASF_EVENT_TYPE_SEVERITY_STATE,
      EFI_ASF_EVENT_OFFSET_SEVERITY_MORE_CRITICAL,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_CRITICAL,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
    }
  },
  {
    EfiAsfMessageTemperatureGenericWarning,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_TEMPERATURE,
      EFI_ASF_EVENT_TYPE_SEVERITY_STATE,
      EFI_ASF_EVENT_OFFSET_SEVERITY_MORE_NONCRITICAL,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONCRITICAL,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
    }
  },
  {
    EfiAsfMessageTemperatureOverCritical,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_TEMPERATURE,
      EFI_ASF_EVENT_TYPE_THRESHOLD_BASED,
      EFI_ASF_EVENT_OFFSET_THRESHOLD_UPPER_CRITICAL,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_CRITICAL,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
    }
  },
  {
    EfiAsfMessageTemperatureOverWarning,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_TEMPERATURE,
      EFI_ASF_EVENT_TYPE_THRESHOLD_BASED,
      EFI_ASF_EVENT_OFFSET_THRESHOLD_UPPER_NONCRITICAL,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONCRITICAL,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
    }
  },
  {
    EfiAsfMessageTemperatureUnderCritical,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_TEMPERATURE,
      EFI_ASF_EVENT_TYPE_THRESHOLD_BASED,
      EFI_ASF_EVENT_OFFSET_THRESHOLD_LOWER_CRITICAL,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_CRITICAL,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
    }
  },
  {
    EfiAsfMessageTemperatureUnderWarning,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_TEMPERATURE,
      EFI_ASF_EVENT_TYPE_THRESHOLD_BASED,
      EFI_ASF_EVENT_OFFSET_THRESHOLD_LOWER_NONCRITICAL,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONCRITICAL,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
    }
  },
  //
  // Voltage
  //
  {
    EfiAsfMessageVoltageGenericCritical,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_VOLTAGE,
      EFI_ASF_EVENT_TYPE_SEVERITY_STATE,
      EFI_ASF_EVENT_OFFSET_SEVERITY_MORE_CRITICAL,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_CRITICAL,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
    }
  },
  {
    EfiAsfMessageVoltageOverCritical,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_VOLTAGE,
      EFI_ASF_EVENT_TYPE_THRESHOLD_BASED,
      EFI_ASF_EVENT_OFFSET_THRESHOLD_UPPER_CRITICAL,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_CRITICAL,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
    }
  },
  {
    EfiAsfMessageVoltageUnderCritical,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_VOLTAGE,
      EFI_ASF_EVENT_TYPE_THRESHOLD_BASED,
      EFI_ASF_EVENT_OFFSET_THRESHOLD_LOWER_CRITICAL,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_CRITICAL,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
    }
  },
  //
  // Fan
  //
  {
    EfiAsfMessageFanGenericCritical,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_FAN,
      EFI_ASF_EVENT_TYPE_SEVERITY_STATE,
      EFI_ASF_EVENT_OFFSET_SEVERITY_MORE_CRITICAL,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_CRITICAL,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
    }
  },
  {
    EfiAsfMessageFanPredictiveFailure,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_FAN,
      EFI_ASF_EVENT_TYPE_DISCRETE_EVENT_PREDICTIVE_FAIL,
      EFI_ASF_EVENT_OFFSET_DISCRETE_EVENT_PREDICTIVE_FAIL_ASSERT,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_CRITICAL,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
    }
  },
  {
    EfiAsfMessageFanLowSpeedCritical,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_FAN,
      EFI_ASF_EVENT_TYPE_THRESHOLD_BASED,
      EFI_ASF_EVENT_OFFSET_THRESHOLD_LOWER_CRITICAL,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_CRITICAL,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
    }
  },
  {
    EfiAsfMessageFanLowSpeedWarning,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_FAN,
      EFI_ASF_EVENT_TYPE_THRESHOLD_BASED,
      EFI_ASF_EVENT_OFFSET_THRESHOLD_LOWER_NONCRITICAL,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONCRITICAL,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Instance
    }
  },
  //
  // Battery
  //
  {
    EfiAsfMessageBatteryLowWarning,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_BATTERY,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_BATTERY_LOW_WARNING,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONCRITICAL,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_POWER_SUPPLY,
      0,  // Instance
    }
  },
  {
    EfiAsfMessageBatteryLowCritical,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_BATTERY,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_BATTERY_LOW_CRITICAL,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_CRITICAL,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_POWER_SUPPLY,
      0,  // Insnce
    }
  },
  {
    EfiAsfMessageBatteryPresenceDetected,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_BATTERY,
      EFI_ASF_EVENT_TYPE_SENSOR_SPECIFIC,
      EFI_ASF_EVENT_OFFSET_BATTERY_PRESENCE_DETECTED,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_MONITOR,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_POWER_SUPPLY,
      0,  // Insnce
    }
  },
  {
    EfiAsfMessagePowerFailure,
    {
      EFI_ASF_MESSAGE_SUBCOMMAND_NORETRANSMIT,
      EFI_ASF_VERSION,
      EFI_ASF_EVENT_SENSOR_TYPE_POWER_SUPPLY,
      EFI_ASF_EVENT_TYPE_SEVERITY_STATE,
      EFI_ASF_EVENT_OFFSET_POWER_SUPPLY_FAILURE,
      EFI_ASF_EVENT_SOURCE_TYPE_ASF10,
      EFI_ASF_EVENT_SEVERITY_CODE_NONRECOVERABLE,
      EFI_ASF_SENSOR_DEVICE,
      EFI_ASF_SENSOR_NUMBER,
      EFI_ASF_ENTITY_SYSTEM_BOARD,
      0,  // Insnce
    }
  },
#endif
};
